### ISSUE TITLE
Not able to install in python 3.6

### ISSUE THREAD

**Issue by sekhar14** [mnaberez/supervisor_twiddler#10]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v_neh43p/supervisor/

**Comment by mnaberez** [comment]
> /tmp/pip-build-v_neh43p/supervisor/

That seems to be an error installing the `supervisor` package, not `supervisor_twiddler`.  At this time, the stable releases of `supervisor` do not yet support Python 3.  However, it can be installed on Python 3 from its git repository.
