### ISSUE TITLE
supervisor_twiddler on Windows

### ISSUE THREAD

**Issue by rchateauneu** [mnaberez/supervisor_twiddler#12]
When install supervisor_twiddler on Windows, it installs its dependency supervisor which runs on Linux only.

It should rather install the Python module supervisor-win https://pypi.org/project/supervisor-win/ , its equivalent on Windows.

What should be changed is, in setup.py, the line:
    install_requires = ['supervisor >= 3.0a10'],

It could be, for example, something like:
    install_requires = ['supervisor-win' if sys.platform.startswith('win') else 'supervisor >= 3.0a10'],

**Comment by mnaberez** [comment]
This package is for use with the [Supervisor](https://pypi.org/project/supervisor/) package only.  The Supervisor package only works on Unix-like systems and does not support Windows.  The other package you mentioned with Windows support is not part of the Supervisor project and not from the Supervisor authors.  I will not support it, sorry.
