### ISSUE TITLE
How to make changes persist after restarting supervisord?

### ISSUE THREAD

**Issue by saulp** [mnaberez/supervisor_twiddler#4]
Hi! I am working on a project that requires starting processes on the fly, and this plugin seems to very nicely fit the bill. I would just like the new processes that I start to be persistent.

What is a recommended way to do this, short of adding to my script the capability to modify the supervisord.conf file itself? (in which case it would probably be simpler to just skip twiddler altogether, and restart supervisord after modifying my config file... but I digress)

Thanks!
Saul

**Comment by natsu90** [comment]
In Ajenti, it has a plugin; a GUI to manage Supervisord, including add & delete program, https://github.com/ajenti/ajenti/tree/1.x/ajenti/plugins/supervisor. I wish I can understand python.

**Comment by mnaberez** [comment]
I actually wrote `supervisor_twiddler` at a time before Supervisor had the ability to reread its config file.  I think the main use case for `supervisor_twiddler` today is for temporary changes that you don't want to persist.

If you want to make changes to the Supervisor and have them persist, I think the best way to do that is to modify or add config files, then use the `supervisorctl`'s config reloading commands:

 - `reread`: Reread the config file to make `supervisord` aware of changes, but don't apply any changes.  This outputs the difference between the on-disk configuration and in-memory configuration like `foo: added` or `bar: removed`.
 - `add`: Add a new program to `supervisord`'s in-memory configuration.
 - `remove`: Remove a program from `supervisord`'s in-memory configuration.
 - `update`: Update changes to a program or use `update all` for the magic "update everything".

You might use this in combination with the `[include]` section, which lets you include extra config files.  You can keep these in a directory like `/etc/supervisor/conf.d`, your program can add or remove files from that directory, then use `update all`.
