### ISSUE TITLE
Error when starting Supervisor

### ISSUE THREAD

**Issue by rajbala** [mnaberez/supervisor_twiddler#5]
I added the twiddler RPC interface to the supervisord.conf file and I see this error when I restart Supervisor.  Any idea as to why this may be happening?

Error: supervisor_twiddler.rpcinterface:make_twiddler_rpcinterface cannot be resolved within [rpcinterface:twiddler]

**Comment by mnaberez** [comment]
You need to shut down `supervisord` fully (the `reread` or `update` commands won't work).  If you are doing that and there are no typos in the `[rpcinterface:twiddler]` section then it means the `supervisor_twiddler` package is not installed, or is not installed into the same environment as `supervisor`.

Another way to check it is from a Python interpreter session:

    $ python
    Python 2.7.8 (default, Oct 16 2014, 20:49:38) 
    >>> import supervisor
    >>> import supervisor_twiddler

Both should be importable and show no error messages.  If you get an error, it is an installation issue.  If it is importable at the Python, then it should work under `supervisord` also.

**Comment by rajbala** [comment]
I copied and pasted the rpcinterface:twiddler portion so there's no typo. 

I do indeed get an error when I try to import supervisor_twiddler because it's not installed under the main system rather it's installed under virtualenv.  When I am in the virtualenv I get no error doing the same import.  

Do you know how do I account for using it with virtualenv under the rpcinterface section?  I can't seem to find that.

**Comment by mnaberez** [comment]
All `rpcinterface` plugins need to run in the same Python environment as Supervisor itself.  If Supervisor is installed on the system Python but the plugin is installed on a virtualenv Python, it is not going to work.  The choices would be to install both Supervisor and the plugin under the virtualenv, or install both Supervisor and the plugin under the system Python.

**Comment by rajbala** [comment]
I think that was definitely my problem.  I was installed Supervisor along with other packages using apt-get, but then install supervisor_twiddler inside of the virtualenv.

I also noticed that supervisor_twiddler uninstalls Supervisor and then reinstalls it.  Why does it do that?

**Comment by mnaberez** [comment]
`supervisor_twiddler` needs Supervisor 3.0a10 or later and declares [a dependency](https://github.com/mnaberez/supervisor_twiddler/blob/1.0.0/setup.py#L53) on it.  A possible reason you saw Supervisor reinstall was to upgrade it to meet this requirement.

**Comment by rajbala** [comment]
Ah!  Understood.  Thanks for the help.

And thanks for making Twiddler.  It's really helpful!

**Comment by fede3u** [comment]
Hey Mike I got the same problem:  Error: supervisor_twiddler.rpcinterface:make_twiddler_rpcinterface cannot be resolved within [rpcinterface:twiddler]

both supervisor and supervisor_twiddler are installed on env, supervisor without this rpc works while as soon as I put it in it spits this error ..

can you please advice? thx 

here is my supervisord.conf:

```
[supervisord]
logfile = %(PROJECT_PATH)s/logs/supervisord.log

[inet_http_server]
port = 9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[rpcinterface:twiddler]
supervisor.rpcinterface_factory = supervisor_twiddler.rpcinterface:make_twiddler_rpcinterface

[group:tweetset]
priority=999                  ; the relative start priority (default 999)

[program:%(PROJECT_NAME)s]
command=%(PROJECT_PATH)s/./start_gunicorn.bash
directory=%(PROJECT_PATH)s
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=%(PROJECT_PATH)s/logs/supervisorconf.log

```
and here are the commands I run to reload the supervisor via Fab:

```
  # stop old supervisor process
  {"action":"sudo", "params":"supervisorctl stop all"},
  {"action":"sudo", "params":"killall supervisord"},

  # Setup supervisor
  {"action":"run", "params":"echo_supervisord_conf > /home/%(SERVER_USERNAME)s/supervisord.conf",
    "message":"Configuring supervisor"},
  {"action":"put_template", "params":{"template":"%(FAB_CONFIG_PATH)s/templates/supervisord.conf",
                                      "destination":"/home/%(SERVER_USERNAME)s/my.supervisord.conf"}},
  {"action":"run", "params":"cat /home/%(SERVER_USERNAME)s/my.supervisord.conf >> /home/%(SERVER_USERNAME)s/supervisord.conf"},
  {"action":"run", "params":"rm /home/%(SERVER_USERNAME)s/my.supervisord.conf"},
  {"action":"sudo", "params":"mv /home/%(SERVER_USERNAME)s/supervisord.conf /etc/supervisord.conf"},
  {"action":"sudo", "params":"supervisord"},
  {"action":"put", "params":{"file":"%(FAB_CONFIG_PATH)s/templates/supervisord-init",
                            "destination":"/home/%(SERVER_USERNAME)s/supervisord-init"}},
  {"action":"sudo", "params":"mv /home/%(SERVER_USERNAME)s/supervisord-init /etc/init.d/supervisord"},
  {"action":"sudo", "params":"chmod +x /etc/init.d/supervisord"},
  {"action":"sudo", "params":"update-rc.d supervisord defaults"},

  # Restart supervisor
  {"action":"sudo", "params":"supervisorctl start all"}
]

```

**Comment by mnaberez** [comment]
Question from @fede3u above was posted again as #8.
