### ISSUE TITLE
Change numprocs at runtime

### ISSUE THREAD

**Issue by jemc** [mnaberez/supervisor_twiddler#6]
I'd like to be able to dynamically change worker process counts based on system load.  Using the supervisor_twiddler approach seems like a good place to start.

I'd like to get feedback from the maintainers - is this a feasible feature request?  Or perhaps work has already been started on it?  If it's feasible and no one is working on it yet, I'd be happy to take a look at tackling it myself.

**Comment by mnaberez** [comment]
Sure, I think it's feasible and probably a good fit for twiddler.  I'm not currently working on it so feel free.

**Comment by jemc** [comment]
After digging into this a bit and trying some various approaches, one big issue I've run into here is that supervisor doesn't expose any runtime intermediate representation of the homogeneous (`program`) groups before they are expanded into processes.

It would be ideal if I could create an RPC method here called `getConfigSection` `updateConfigSection` that export the config parser section attributes and apply a set of attribute changes to a config parser section respectively.  I was planning to fetch the original config section for the program group I wanted to modify, apply a change to the numprocs attribute, recreate the internal expanded representation of the individual process configs, then see which process configs were changed or added or removed from the original set of process configs, applying the change similar to how `addProgramToGroup` and `removeProcessFromGroup` already work.

However, as far as I can tell, supervisor does not permanently store the config parser instance from the last config file read.  Instead, it opens the file, reads it into the config parser, expands includes, applies environment expansions, and expands sections into their internal representation of individual process properites per group, which have no memory of the original group definition from the config file (pre-expansion).

Because all of this process happens in one cascade of functions, it's not possible to hook into this process in any meaningful way without an invasive monkey patch (as far as I can tell).  I think this probably requires some changes to supervisor itself to work in the general case as I described.

I think I can make `addProgramToGroup` and `removeProcessFromGroup` work for me in my specific case if I forget about using config files and configure supervisor exclusively via XMLRPC.  Hopefully this comment will help someone else if they care to take the extra time with this.

**Comment by mnaberez** [comment]
> However, as far as I can tell, supervisor does not permanently store the config parser instance from the last config file read.

It does not store the ConfigParser instance, instead its contents are converted into ProcessConfig objects that are stored.
