### ISSUE TITLE
rpm anywhere?

### ISSUE THREAD

**Issue by cjw296** [mnaberez/supervisor_twiddler#7]
Hi,

Has anyone packages supervisor_twiddler as an rpm?

Chris

**Comment by mnaberez** [comment]
I publish `supervisor_twiddler` as a Python package on [PyPI](https://pypi.python.org/pypi/supervisor_twiddler).  It can be installed with a command like `pip install supervisor_twiddler`.  

I understand some people only want to use system packages (`deb`, `rpm`).  I can appreciate that but I don't have enough bandwidth to generate those packages also, sorry.
