### ISSUE TITLE
Error when starting Supervisor ...

### ISSUE THREAD

**Issue by fede3u** [mnaberez/supervisor_twiddler#8]
Hey Mike I got this problem: Error: supervisor_twiddler.rpcinterface:make_twiddler_rpcinterface cannot be resolved within [rpcinterface:twiddler]

both supervisor and supervisor_twiddler are installed on env, supervisor without this rpc works while as soon as I put it in it spits this error ..

can you please advice? thx for your help!!!

here is my supervisord.conf:

```
[supervisord]
logfile = %(PROJECT_PATH)s/logs/supervisord.log

[inet_http_server]
port = 9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[rpcinterface:twiddler]
supervisor.rpcinterface_factory = supervisor_twiddler.rpcinterface:make_twiddler_rpcinterface

[group:tweetset]
priority=999                  ; the relative start priority (default 999)

[program:%(PROJECT_NAME)s]
command=%(PROJECT_PATH)s/./start_gunicorn.bash
directory=%(PROJECT_PATH)s
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=%(PROJECT_PATH)s/logs/supervisorconf.log
```

and here are the commands I run to reload the supervisor via Fab:

```
  # stop old supervisor process
  {"action":"sudo", "params":"supervisorctl stop all"},
  {"action":"sudo", "params":"killall supervisord"},

  # Setup supervisor
  {"action":"run", "params":"echo_supervisord_conf > /home/%(SERVER_USERNAME)s/supervisord.conf",
    "message":"Configuring supervisor"},
  {"action":"put_template", "params":{"template":"%(FAB_CONFIG_PATH)s/templates/supervisord.conf",
                                      "destination":"/home/%(SERVER_USERNAME)s/my.supervisord.conf"}},
  {"action":"run", "params":"cat /home/%(SERVER_USERNAME)s/my.supervisord.conf >> /home/%(SERVER_USERNAME)s/supervisord.conf"},
  {"action":"run", "params":"rm /home/%(SERVER_USERNAME)s/my.supervisord.conf"},
  {"action":"sudo", "params":"mv /home/%(SERVER_USERNAME)s/supervisord.conf /etc/supervisord.conf"},
  {"action":"sudo", "params":"supervisord"},
  {"action":"put", "params":{"file":"%(FAB_CONFIG_PATH)s/templates/supervisord-init",
                            "destination":"/home/%(SERVER_USERNAME)s/supervisord-init"}},
  {"action":"sudo", "params":"mv /home/%(SERVER_USERNAME)s/supervisord-init /etc/init.d/supervisord"},
  {"action":"sudo", "params":"chmod +x /etc/init.d/supervisord"},
  {"action":"sudo", "params":"update-rc.d supervisord defaults"},

  # Restart supervisor
  {"action":"sudo", "params":"supervisorctl start all"}
]

```

**Comment by mnaberez** [comment]
> both supervisor and supervisor_twiddler are installed on env, supervisor without this rpc works while as soon as I put it in it spits this error ..

`supervisord` just uses Python's import machinery to load plugins.  If `supervisord` can't load `supervisor_twiddler`, then `supervisor_twiddler` isn't installed in the same Python environment as `supervisord`.  A way to check for this is:

```
$ python
Python 2.7.12 (default, Sep 28 2016, 18:41:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import supervisor
>>> import supervisor_twiddler
```

You should be able to import both without errors.

**Comment by mnaberez** [comment]
There isn't a way for this package or the Supervisor package to affect this error.  Either Python imports that `supervisor_twiddler` package or it doesn't.  If it doesn't, the package is not installed or is installed in the wrong Python environment.

**Comment by fede3u** [comment]
Thx Mike, 
I understand your point and it all works in local the problem arises once I bring it to production on the ubuntu server ... can you give me an int on how to make the supervisor run on the env as I have been cracking my head on this for 2 days now and I have no clue ... I really appreciate your help.

btw both supervisor and supervisor_twiddler are installed on a env and not anywhere else so I don't get how the supervisor works without the twiddler but t doesn't once i add that part..

Thx a lot
